server:
  port: 2019
spring:
  application:
    name: ebag-correct-home

 

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka

mybatis:
  mapper-locations: classpath:mapper/*.xml

security:
  oauth2:
    resource:
      id: ebag-correct-home
      user-info-uri: http://localhost:9001/oauth/user
      prefer-token-info: false

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql

logging:
  level:
    com:
      ysb:
        ebag:
          correct:
            home:
              controller: WARN
              dao: DEBUG